# permissions for end users to edit hellos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hello-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-example1
    app.kubernetes.io/part-of: operator-example1
    app.kubernetes.io/managed-by: kustomize
  name: hello-editor-role
rules:
- apiGroups:
  - vakifbank.v7k
  resources:
  - hellos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vakifbank.v7k
  resources:
  - hellos/status
  verbs:
  - get
